name: raspi-temp
author: ccs
email: nobody@nowhere.com
url: http://example.com
version: '0.1'
title: 'raspi temperature'
icon: terminal
# dependency on Core is required for UI plugins
dependencies:
    - !!python/object:aj.plugins.PluginDependency {
        plugin_name: core
    }
    - !!python/object:aj.plugins.OptionalPluginDependency {
      plugin_name: dashboard
    }
    # - !!python/object:aj.plugins.ModuleDependency {
    #   module_name: requests
    # }
    # - !!python/object:aj.plugins.BinaryDependency {
    #   binary_name: curl
    # }
resources:
    - 'resources/js/module.es'
    - 'resources/js/controllers/index.controller.es'
    - 'resources/partial/raspi-temp.html'
    - 'ng:raspi.raspi-temp'
    # - 'ng:my.plugin.angular-submodule'
    # - 'resources/module.js'
    # - 'resources/module.coffee'
    # - 'resources/styles.css'
    # - 'resources/styles.less'
